version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
      day: thursday
    ignore:
      # htmluibuild is explicitly updated by us
      - dependency-name: "github.com/kopia/htmluibuild"
    groups:
      # create large PR upgrading multiple infrastructure dependencies in one shot,
      # only include upstream dependencies that are stable and have somewhat
      # regular releases which would be otherwise hard to manually manage.
      common-golang-dependencies:
        patterns:
        - "cloud.google.com/*"
        - "github.com/aws/aws-sdk-go/*"
        - "github.com/Azure/azure-sdk-for-go/sdk/*"
        - "github.com/minio/minio-go/*"
        - "golang.org/x/*"
        - "google.golang.org/*"
      telemetry-dependencies:
        patterns:
        - "github.com/prometheus/*"
        - "go.opentelemetry.io/*"
