version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/app"
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/htmlui"
    schedule:
      interval: monthly
