name: Linux CI
on:
  pull_request:
    branches: [ main, local-main ]
  push:
    branches: [ main, local-main, run-ci, linux-ci ]
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    -
      name: Set up Go.
      id: go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      name: Build
      run: make build-current-os-noui
    -
      name: Lint
      run: make lint vet
    -
      name: Upload Logs
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    -
      name: Set up Go.
      id: go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      name: Tests
      run: make test
      continue-on-error: ${{ github.event_name != 'pull_request' }}
    -
      name: Upload Logs
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    -
      name: Set up Go.
      id: go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      name: Integration Tests
      run: make -j2 ci-integration-tests
      continue-on-error: ${{ github.event_name != 'pull_request' }}
    -
      name: Upload Logs
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
  race:
    name: Race Detector
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    -
      name: Set up Go.
      id: go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      name: Unit Tests
      run: make -j2 test UNIT_TEST_RACE_FLAGS=-race UNIT_TESTS_TIMEOUT=1200s
      continue-on-error: ${{ github.event_name != 'pull_request' }}
    -
      name: Upload Logs
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
