name: Linux CI
on:
  pull_request:
    branches: [ main, local-main ]
  push:
    branches: [ main, local-main, run-ci, linux-ci ]
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  # environment variables shared between build steps
  # set (to any value other than false) to trigger random unicode filenames testing (logs may be difficult to read)
  ENABLE_UNICODE_FILENAMES: "true"
  # set (to any value other than false) to trigger very long filenames testing
  ENABLE_LONG_FILENAMES: "true"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
    -
      name: Set up Go.
      id: go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      name: Setup tools
      run: make -j4 ci-setup
    -
      name: Tests
      run: make -j4 ci-tests
    -
      name: Upload Logs
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
