name: SSA Checks
on:
  pull_request:
    branches: [ main, master, local-main ]
  push:
    branches: [ main, master, local-main ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ssa-checks:
    name: SSA Checks
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      id: go
      name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
    # -
    #   name: Build Kopia
    #   run: make install
    -
      id: govulncheck
      name: Vuln Check
      uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4
      with:
        go-version-file: 'go.mod'
        repo-checkout: false
        cache: false
    -
      name: GoKart
      # continue-on-error: true
      run: |
        exit 0 # gokart is crashing, so exit early
        set -xue
        go install github.com/praetorian-inc/gokart@latest
        gokart scan --sarif --output gokart-results.sarif

    # -
    #   # Upload the SARIF file generated by GoKart
    #   name: Upload GoKart results
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: gokart-results.sarif
