name: Sync Fork
on:
  push:
    branches: [ main, local-main ]
  schedule:
    - cron: '30 5 * * 1-5'
      timezone: "America/Los_Angeles"
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'target branch for repo sync'
        default: 'master'
        required: true
        type: choice
        options:
        - master
        - upstream
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Sync Fork
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    -
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit
    -
      name: Sync
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh repo sync ${{ github.repository }} -b ${{ inputs.target_branch || 'master' }}
